---
# Clean up HAProxy + Keepalived + Self-Signed SSL Setup
# Hosts: ELB1, ELB2

- name: Cleanup HAProxy & Keepalived & SSL from ELBs
  hosts:
    - ELB1
    - ELB2
  become: true
  gather_facts: true

  vars:
    domain: "{{ DOMAIN | default('lab.ing5.com') }}"
    haproxy_cert_dir: /etc/haproxy/certs
    haproxy_cfg: /etc/haproxy/haproxy.cfg
    keepalived_cfg: /etc/keepalived/keepalived.conf

  tasks:
    - name: Stop and disable HAProxy
      service:
        name: haproxy
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Stop and disable Keepalived
      service:
        name: keepalived
        state: stopped
        enabled: no
      ignore_errors: true

    - name: Remove HAProxy config
      file:
        path: "{{ haproxy_cfg }}"
        state: absent

    - name: Remove Keepalived config
      file:
        path: "{{ keepalived_cfg }}"
        state: absent

    - name: Remove SSL directory and certificates
      file:
        path: "{{ haproxy_cert_dir }}"
        state: absent

    - name: Close HTTP port 80 (firewalld)
      firewalld:
        port: 80/tcp
        state: disabled
        permanent: true
        immediate: true
      ignore_errors: true

    - name: Close HTTPS port 443 (firewalld)
      firewalld:
        port: 443/tcp
        state: disabled
        permanent: true
        immediate: true
      ignore_errors: true

    - name: Reload firewalld
      command: firewall-cmd --reload
      ignore_errors: true

    - name: Remove ELB host entries from /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "{{ item }}"
        state: absent
      loop:
        - "ELB1"
        - "ELB2"
      ignore_errors: true

    - name: Purge HAProxy & Keepalived packages (optional)
      package:
        name:
          - haproxy
          - keepalived
        state: absent
      ignore_errors: true

    - name: Clean VIP (remove any leftover virtual IP)
      shell: |
        ip addr flush label eth0:vip || true
      ignore_errors: true
