---
- name: Install and configure HAProxy + Keepalived
  hosts: all
  gather_facts: true
  vars:
    haproxy_backend_port: 80
    haproxy_cfg_path: /etc/haproxy/haproxy.cfg
    haproxy_cert_dir: /etc/haproxy/certs
    vip_address: 192.168.74.254
    vip_interface: ens33

  tasks:
    - block:
        - name: Install HAProxy and Keepalived
          package:
            name: "{{ item }}"
            state: present
          loop:
            - haproxy
            - keepalived

        - name: Ensure HAProxy certs dir exists
          file:
            path: "{{ haproxy_cert_dir }}"
            state: directory
            mode: "0755"

        - name: Configure Keepalived
          copy:
            dest: /etc/keepalived/keepalived.conf
            mode: "0644"
            content: |
              vrrp_instance VI_1 {
                  state {{ 'MASTER' if inventory_hostname == 'ELB-I' else 'BACKUP' }}
                  interface {{ vip_interface }}
                  virtual_router_id 51
                  priority {{ '100' if inventory_hostname == 'ELB-I' else '90' }}
                  advert_int 1
                  authentication {
                      auth_type PASS
                      auth_pass 1234
                  }
                  virtual_ipaddress {
                      {{ vip_address }}
                  }
              }

        - name: Start Keepalived and ensure enabled
          service:
            name: keepalived
            state: started
            enabled: true

        - name: Configure HAProxy
          copy:
            dest: "{{ haproxy_cfg_path }}"
            mode: "0644"
            content: |
              global
                log /dev/log local0
                log /dev/log local1 notice
                daemon
                maxconn 2048

              defaults
                log     global
                mode    http
                option  httplog
                option  dontlognull
                timeout connect 5000
                timeout client  50000
                timeout server  50000

              frontend https_in
                bind *:443 ssl crt {{ haproxy_cert_dir }}/iso.pem
                default_backend waf_backend

              backend waf_backend
                balance roundrobin
                {% for host in ['WAF-I', 'WAF-II'] %}
                server {{ host }} {{ hostvars[host]['ansible_host'] }}:{{ haproxy_backend_port }} check
                {% endfor %}

        - name: Start HAProxy and ensure enabled
          service:
            name: haproxy
            state: started
            enabled: true
      when: inventory_hostname in ['ELB-I', 'ELB-II']
