---
- name: Cleanup K3s HA cluster (RHEL 10)
  hosts: all
  become: true
  vars:
    cp_nodes:
      - CP1
      - CP2
      - CP3
    agent_nodes:
      - W1
      - W2
      - W3
      - W4
    k3s_dirs:
      - /etc/rancher/k3s
      - /var/lib/rancher/k3s
      - /var/lib/kubelet
      - /var/lib/cni
      - /run/k3s
      - /usr/local/bin/k3s
    k3s_service: k3s

  tasks:
    # -----------------
    # Stop K3s services
    # -----------------
    - name: Stop K3s service
      ansible.builtin.systemd:
        name: "{{ k3s_service }}"
        state: stopped
      ignore_errors: true

    - name: Disable K3s service
      ansible.builtin.systemd:
        name: "{{ k3s_service }}"
        enabled: no
      ignore_errors: true

    # -----------------
    # Remove K3s binaries and data directories
    # -----------------
    - name: Remove K3s directories and files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ k3s_dirs }}"

    # -----------------
    # Remove cluster token file (if exists)
    # -----------------
    - name: Remove temporary cluster token
      ansible.builtin.file:
        path: /tmp/k3s_cluster_token
        state: absent

    - name: Remove per-node token files (agents and cp joins)
      ansible.builtin.file:
        path: "/tmp/k3s_token_{{ inventory_hostname }}"
        state: absent

    # -----------------
    # Remove kubectl alias from .bashrc
    # -----------------
    - name: Remove kubectl alias
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "alias k='kubectl'"
        state: absent

    - name: Reload bashrc
      ansible.builtin.shell: source /root/.bashrc
      ignore_errors: true

    # -----------------
    # Disable firewalld if desired (uncomment to remove)
    # -----------------
    - name: Stop and disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no
